# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180731_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseimage',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.Exercise', verbose_name='Exercise'),
        ),
    ]
