# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-03 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180730_2036'),
        ('exercises', '0008_auto_20180802_0658'),
    ]

    operations = [
    ]
