# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(default='Planned', max_length=15, verbose_name='Meal Type'),
        ),
    ]
