# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_reg_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reg_flag',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
