# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180808_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reg_flag',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
