# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180808_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
