# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_create_use_rest_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_use_rest_api',
            field=models.BooleanField(default=False, help_text='Allow user to create users via REST API'),
        ),
    ]
