# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180809_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
