# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
