# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.CharField(max_length=50, null=True, verbose_name='Period'),
        ),
    ]
