# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_schedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - 1 week plan'), ('Mesocycle', 'Mesocycle - 2 to 6 week plan'), ('Macrocycle', 'Macrocycle - 1 year plan')], max_length=50, null=True, verbose_name='Period'),
        ),
    ]
