# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 07:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180815_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.CharField(choices=[(None, 'No period'), ('Microcycle', 'Microcycle(1 week)'), ('Mesocycle', 'Mesocycle(2-6 weeks)'), ('Macrocycle', 'Macrocycle(1 year)')], max_length=50, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Duration'),
        ),
    ]
