# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-17 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180817_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='WorkoutSession'),
        ),
    ]
