# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0020_auto_20180816_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='buddy',
            field=models.ManyToManyField(null=True, related_name='workout_buddy_user', to=settings.AUTH_USER_MODEL, verbose_name='users sharing workout with schedule owner'),
        ),
    ]
