# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20180816_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='workoutsession'),
        ),
    ]
