# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-22 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20180822_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='buddy',
            field=models.ManyToManyField(blank=True, help_text='Add buddy/partner to your workout schedule', related_name='user_workout_buddy', to=settings.AUTH_USER_MODEL, verbose_name='Workout buddy/partner'),
        ),
    ]
