# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-23 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0025_auto_20180822_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBuddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Workout buddy/partner')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='buddy',
        ),
        migrations.AddField(
            model_name='schedulebuddy',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Schedule', verbose_name='schedule'),
        ),
    ]
